### ISSUE TITLE
Add available formats to wiki

### ISSUE THREAD

**Issue by netcodedev** [ThatsNasu/Ansi#5]
Just a suggestions: Since there are not many you could add the available formattings to the [wiki page](https://github.com/thatsnasu/ansi/wiki/Formatting-with-predefined-Formats)

**Comment by ThatsNasu** [comment]
would mean for consistency i would have to do the same with the colors. But i could hint to the javadoc for some more info about the colors and format options

**Comment by ThatsNasu** [comment]
note for the documentation on first occurance of colors and formats in the wiki made.
